// ********************************************************************************
// <summary>
/// 
/// </summary>
/// <created>ʆϒʅ,09.04.2019</created>
/// <changed>ʆϒʅ,09.04.2019</changed>
// ********************************************************************************

#pragma once


#ifndef PRODUCT_VERSION_MAJOR
#define PRODUCT_VERSION_MAJOR @PRODUCT_VERSION_MAJOR@
#endif // !PRODUCT_VERSION_MAJOR

#ifndef PRODUCT_VERSION_MINOR
#define PRODUCT_VERSION_MINOR @PRODUCT_VERSION_MINOR@
#endif // !PRODUCT_VERSION_MINOR

#ifndef PRODUCT_VERSION_PATCH
#define PRODUCT_VERSION_PATCH @PRODUCT_VERSION_PATCH@
#endif // !PRODUCT_VERSION_PATCH

#ifndef PRODUCT_VERSION_BUILD
#define PRODUCT_VERSION_BUILD @PRODUCT_VERSION_BUILD@
#endif // !PRODUCT_VERSION_BUILD

#ifndef FILE_VERSION_MAJOR
#define FILE_VERSION_MAJOR @PRODUCT_VERSION_MAJOR@
#endif // !FILE_VERSION_MAJOR

#ifndef FILE_VERSION_MINOR
#define FILE_VERSION_MINOR @PRODUCT_VERSION_MINOR@
#endif // !FILE_VERSION_MINOR

#ifndef FILE_VERSION_PATCH
#define FILE_VERSION_PATCH @PRODUCT_VERSION_PATCH@
#endif // !FILE_VERSION_PATCH

#ifndef FILE_VERSION_BUILD
#define FILE_VERSION_BUILD @PRODUCT_VERSION_BUILD@
#endif // !FILE_VERSION_BUILD

//#define PRODUCT_VERSION_MAJOR_MINOR_STR
//__TO_STRING ( PRODUCT_VERSION_MAJOR ) "."
//__TO_STRING ( PRODUCT_VERSION_MINOR )
//
//#define PRODUCT_VERSION_MAJOR_MINOR_PATCH_STR
//PRODUCT_VERSION_MAJOR_MINOR_STR "."
//__TO_STRING ( PRODUCT_VERSION_PATCH )
//
//#define PRODUCT_VERSION_FULL_STR
//PRODUCT_VERSION_MAJOR_MINOR_PATCH_STR "."
//__TO_STRING ( PRODUCT_VERSION_BUILD )
//
//#define PRODUCT_VERSION_MAJOR_MINOR_PATCH_STR
//PRODUCT_VERSION_MAJOR_MINOR_STR "."
//__TO_STRING ( PRODUCT_VERSION_PATCH )

#define PRODUCT_VERSION_RESOURCE PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH, PRODUCT_VERSION_BUILD

#define PRODUCT_VERSION_RESOURCE_STR __TO_STRING ( PRODUCT_VERSION_MAJOR ) "." __TO_STRING ( PRODUCT_VERSION_MINOR ) "." __TO_STRING ( PRODUCT_VERSION_PATCH ) "." __TO_STRING ( PRODUCT_VERSION_BUILD ) "\0"

#define FILE_VERSION_RESOURCE FILE_VERSION_MAJOR, FILE_VERSION_MINOR, FILE_VERSION_PATCH, FILE_VERSION_BUILD

#define FILE_VERSION_RESOURCE_STR __TO_STRING ( FILE_VERSION_MAJOR ) "." __TO_STRING ( FILE_VERSION_MINOR ) "." __TO_STRING ( FILE_VERSION_PATCH ) "." __TO_STRING ( FILE_VERSION_BUILD ) "\0"

#ifndef PRODUCT_ICON
#define PRODUCT_ICON "@PRODUCT_ICON@"
#endif // !PRODUCT_ICON

#ifndef PRODUCT_COMMENTS
#define PRODUCT_COMMENTS "@PRODUCT_COMMENTS@\0"
#endif // !PRODUCT_COMMENTS

#ifndef PRODUCT_COMPANY_NAME
#define PRODUCT_COMPANY_NAME "@PRODUCT_COMPANY_NAME@\0"
#endif // !PRODUCT_COMPANY_NAME

#ifndef PRODUCT_COMPANY_COPYRIGHT
#define PRODUCT_COMPANY_COPYRIGHT "@PRODUCT_COMPANY_COPYRIGHT@\0"
#endif // !PRODUCT_COMPANY_COPYRIGHT

#ifndef PRODUCT_COMPANY_DESCRIPTION
#define PRODUCT_COMPANY_DESCRIPTION "@PRODUCT_COMPANY_DESCRIPTION@\0"
#endif // !PRODUCT_COMPANY_DESCRIPTION

#ifndef PRODUCT_INTERNAL_NAME
#define PRODUCT_INTERNAL_NAME "@PRODUCT_INTERNAL_NAME@\0"
#endif // !PRODUCT_INTERNAL_NAME

#ifndef PRODUCT_ORIGINAL_FILENAME
#define PRODUCT_ORIGINAL_FILENAME "@PRODUCT_ORIGINAL_FILENAME@\0"
#endif // !PRODUCT_ORIGINAL_FILENAME

#ifndef PRODUCT_BUNDLE
#define PRODUCT_BUNDLE "@PRODUCT_BUNDLE@\0"
#endif // !PRODUCT_BUNDLE
